name: Build, test and deploy project

on:
  push: # trigger on git push
  workflow_dispatch: # allow manual trigger

jobs:
  build-and-test-and-deploy-project:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create pypi config file
        run: 'echo -e "---\n:rubygems_api_key: = ${{ secrets.RUBYGEMS_API_KEY }}" > credentials'

      - name: Install prerequisites
        run: sudo apt-get install --yes socat

      - name: Configure gnupg and ssh on the host
        run: |
          mkdir $HOME/.ssh
          echo "AddKeysToAgent yes" > $HOME/.ssh/config
          mkdir $HOME/.gnupg
          echo "batch" > $HOME/.gnupg/gpg-agent.conf
          echo "enable-ssh-support" >> $HOME/.gnupg/gpg-agent.conf

      - name: Add bitboard ssh key to agent
        run: |
          gpg-connect-agent updatestartuptty /bye
          export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
          chmod 600 features/cucumber/support/fixtures/takelage-bitboard/id_rsa.myuser
          ssh-add features/cucumber/support/fixtures/takelage-bitboard/id_rsa.myuser

      - name: Add host.docker.internal to /etc/hosts
        run: echo "127.0.0.1 host.docker.internal" | sudo tee --append /etc/hosts

      - name: Set up ruby
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: 2.7

      - name: Install tau
        run: gem install takelage

      - name: Configure tau
        run: 'echo "docker_entrypoint_options: --no-git --no-gopass" >> $HOME/.takelage.yml'

      - name: Configure docker daemon
        run: |
          echo '{ "cgroup-parent": "/actions_job", "insecure-registries": [ "host.docker.internal:5005" ] }' > /tmp/daemon.json
          sudo mv /tmp/daemon.json /etc/docker/daemon.json
          sudo systemctl restart docker.service

      - name: Pull takelage image
        run: tau update

      - name: Start an instance of takelage
        run: tau docker container daemon

      - name: Lint ruby
        run: tau docker container command "rake rubylint"

      - name: Run unit tests
        run: tau docker container command "rake test"

#      - name: Run cucumber features
#        run: tau docker container command "SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket) rake features"

      - name: Clean docs
        run: tau docker container command "rake doc:clean"

      - name: Build docs
        run: tau docker container command "rake doc:build"

      - name: Commit docs
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: doc
          commit-message: Update docs

      - name: Clean gems
        run: tau docker container command "gem:clean"

      - name: Build gem
        run: tau docker container command "gem:build"

      - name: Move gem
        run: tau docker container command "gem:move"

      - name: Push gem
        run: tau docker container command "gem:push"
